# Class for storage of the results from the transcription service at runtime. 
class TranscriptionResults:
    # Initialize TranscriptionResults Object. Assign the input variables to the class attributes.
    # 
    # Class attributes:  
    # ids: List that contains the IDs from the database table where the transcription results are stored. 
    # originalSentences: List that contains the original sentences (Labels in form of correct transcripts) from the test dataset. 
    # originalSentanceIds: List that contains the IDs from the database table of the test dataset. 
    # transcripts: List that contains the transcripts generated by the TranscriptionService. 
    # 
    # Input: 
    # ids: List that contains the IDs from the database table where the transcription results are stored. Default value = empty list.
    # originalSentences: List that contains the original sentences (Labels in form of correct transcripts) from the test dataset. Default value = empty list.
    # originalSentanceIds: List that contains the IDs from the database table of the test dataset. Default value = empty list.
    # transcripts: List that contains the transcripts generated by the TranscriptionService. Default value = empty list. 
    def __init__(self, ids=[], originalSentences=[], originalSentanceIds=[], transcripts=[]):
        self.ids = ids
        self.originalSentences = originalSentences
        self.originalSentanceIds = originalSentanceIds
        self.transcripts = transcripts

    # Add a new pair of transcription result data to the class attributes. 
    # 
    # Input:
    # newOriginalSentanceId: Integer containing The database ID of the original sentence (test dataset label) 
    #                        from the test dataset corresponding to the newTranscript. 
    # newTranscript: String containing the transcript generated by the TranscriptionService. 
    def addTranscriptionResult(self, newOriginalSentanceId, newTranscript):
        self.originalSentanceIds.append(newOriginalSentanceId)
        self.transcripts.append(newTranscript)

    # Return the ID for a given index from the ids class attribute.
    # 
    # Input:
    # index: Integer for identifying the desired entry. 
    # 
    # Return: 
    # Integer containing the ID from the ids class attribute corresponding to the index number. 
    def getId(self, index):
        return self.ids[index]

    # Return the original sentence for a given index from the originalSentences class attribute.
    # 
    # Input:
    # index: Integer for identifying the desired entry. 
    # 
    # Return: 
    # String containing the original sentence from the originalSentences class attribute corresponding to the index number. 
    def getOriginalSentence(self, index):
        return self.originalSentences[index]

    # Return the transcript for a given index from the transcripts class attribute.
    # 
    # Input:
    # index: Integer for identifying the desired entry. 
    # 
    # Return: 
    # String containing the transcript from the transcripts class attribute corresponding to the index number. 
    def getTranscript(self, index):
        return self.transcripts[index]

    # Format the transcription result data as SQLite-insert-query and return it.
    # 
    # Return:
    # Transcription result data formatted as SQLite-insert-query-string.  
    def getTranscriptionResultDataAsSqliteQuery(self):
        sqlQuery = "INSERT INTO TranscriptionResults (originalSentaceId, transcript) VALUES"
        for index in range(0, self.len()):
            sqlQuery += f"({self.originalSentanceIds[index]}, '{self.transcripts[index]}'),"
        return sqlQuery[:-1] + ";"

    # Return the number of transcription results stored in the class attributes.
    # 
    # Return:
    # Integer containing the number of transcription results stored in the class attributes. 
    def len(self):
        return len(self.transcripts)
